### ISSUE TITLE
Not so much a bug as a query...

### ISSUE THREAD

**Issue by steveharman** [Sunjammer/nfuse#22]
After running nfuse I think everything went to plan, I have my node_modules folder and now a new NPN-Packages folder courtesy of nfuse - but am not having much luck figuring out the correct path syntax for my require() statement.  Can you help at all please?

I'm experimenting with the firebase node module so inside <fuse project root>node_modules I have amongst other modules a firebase folder containing firebase.js - which I'm attempting to require() in my Fuse app.  I've tried to reference it like this:

`var firebase = require('./node_modules/firebase/firebase.js');
`
But Fuse keeps telling me the module can't be found.

```
LOG: Error: JavaScript error in MainView.ux line 3: Name: Fuse.Scripting.Error
    Error message: require(): module not found: node_modules/firebase/firebase.js
    File name: MainView.ux
    Line number: 3
    Source line: var firebase = require('node_modules/firebase/firebase.js');
```
A quick example would be very much appreciated.  

Thanks,

Steve

**Comment by Sunjammer** [comment]
Hey steve, the idea is that you would require your dependency the same way you would in nodejs, so in your case it would probably just be `require('firebase')`

YMMV, of course ;)
