### ISSUE TITLE
Hashbang doesn't like carriage returns

### ISSUE THREAD

**Issue by sebbert** [Sunjammer/nfuse#6]
When installing and running `nfuse`, I get the following error:

```
$ npm install -g nfuse
$ nfuse
env: node\r: No such file or directory
```

Seems that env assumes LF while the file is CRLF, making it think that the carriage return is part of the name of the node binary. Changing the file to use LF line endings makes it work wonders.

---
- macOS El Capitan 10.11.3
- Node.js v6.1.0

**Comment by Sunjammer** [comment]
Known. I need to push with LF rather than CRLF
